### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by makiharukawa** [Dyonovan/Named-Enchantments#1]
https://gist.github.com/makiharukawa/4afdcb948686ce10e7f4bcd230114521
Sorry for taking a while!

**Comment by Dyonovan** [comment]
Which dutch language would you like it under. it goes by aa_aa format. As soon as you let me know, I will add it and update curse


Dutch - Belgium | nl | nl-be 
Dutch - Netherlands | nl | nl-nl

**Comment by Dyonovan** [comment]
https://gyazo.com/70b0668b42fc41a294f9d432437d41ba

**Comment by makiharukawa** [comment]
nl-nl works, and also in the screenshot you put  i made a typo, i'll edit it rn

**Comment by Dyonovan** [comment]
Fixed and uploaded. https://minecraft.curseforge.com/projects/named-enchantments/files/2701992
